---
title: "Reproducible Research: Peer Assessment 1"
output: 
  html_document:
    keep_md: true
---


## Loading and preprocessing the data
Steps to load and process the data

```{R Load and Clean Process}
library(ggplot2)

      # unzip file if not previously done and read csv
if (exists("activity.csv")) {
      activity <- read.csv("activity.csv")
}     else {
      unzip("./activity.zip")
      activity <- read.csv("activity.csv")
}

# summarize data, omit NA values, set columns and format date field
totalStepsbyDay <- with(activity,aggregate(steps, by = list(date),sum, na.rm = TRUE))
colnames(totalStepsbyDay) <- c('Date','Steps')
totalStepsbyDay$Date <- as.Date(totalStepsbyDay$Date,"%Y-%m-%d")

# summarize data average daily activity pattern and set column names
avgDailyPattern <- with(activity,aggregate(steps, by = list(interval),mean, na.rm = TRUE))
colnames(avgDailyPattern) <- c('Interval','AvgSteps')

```

## What is mean total number of steps taken per day?

```{R Hist}

hist(totalStepsbyDay$Steps, xlab = "Total Steps", 
     main = "Histogram Total Steps Taken each Day")
```

Mean of total steps taken per day excluding NA values

```{R Mean}

mean(totalStepsbyDay$Steps)

```

Median of total steps taken per day excluding NA values

```{R Median}

median(totalStepsbyDay$Steps)

```

## What is the average daily activity pattern?

```{R time}

plot(avgDailyPattern$Interval,avgDailyPattern$AvgSteps,type = "l",
     xlab = "Interval", ylab = "Average Steps", main = "Time Series of Average Steps Taken")

```

Which 5 minute interval on average contains max number of steps

```{R which}

avgDailyPattern[which.max(avgDailyPattern$AvgSteps),]

```

## Imputing missing values

2304 rows in steps field have NA as shown in summary of steps column

```  {R rowsNA}

summary(activity$steps)

```

Will utilize average by 5 minute interval to replace steps in the 2304 records having NA values in the steps field.  Steps to recreate new data set.

``` {R newdataset}

# steps to calculate mean by interval and replace NA values with it
activity2 <- activity
activity2$newSteps <- ave(activity2$steps, activity2$interval, FUN = function(x)mean(x[!is.na(x)]))
activity2$steps <- ifelse(is.na(activity2$steps),activity2$newSteps,activity2$steps)
totalStepsbyDayClean <- with(activity2,aggregate(steps, by = list(date),sum))
colnames(totalStepsbyDayClean) <- c('Date','Steps')
totalStepsbyDayClean$Date <- as.Date(totalStepsbyDayClean$Date,"%Y-%m-%d")

hist(totalStepsbyDayClean$Steps, xlab = "Total Steps", 
     main = "Histogram Total Steps Taken each Day")
```

Mean of total steps taken per day after imputing NA values

```{R newMean}

mean(totalStepsbyDayClean$Steps)

```

Median of total steps taken per day after imputing NA values

```{R newMedian}

median(totalStepsbyDayClean$Steps)

```

Using the mean to replace NA values has cause mean and median values to be the same.


## Are there differences in activity patterns between weekdays and weekends?

Creating new factor variable to identify records as weekday or weekend

``` {R newfactor}

# steps to calculate average pattern activity on imputed dataset
activity3 <- activity2
activity3$date <- as.Date(activity3$date,"%Y-%m-%d")
activity3$type <- factor(grepl("S.+",weekdays(activity3$date)),levels = c(FALSE,TRUE),
                         labels = c("weekday","weekend"))
avgDailyPatternClean <- with(activity3,aggregate(steps, by = list(interval,type),mean))
colnames(avgDailyPatternClean) <- c('Interval','Type','AvgSteps')
avgDailyPatternClean <- with(activity3,aggregate(steps, by = list(interval,type),mean))
colnames(avgDailyPatternClean) <- c('Interval','Type','AvgSteps')

```

Plot of data by weekend or weekday highlights the differences in averages for a weekday vs a weekend

``` {R typeplot}

qplot(Interval,AvgSteps,data = avgDailyPatternClean, facets = Type~. , geom = "line",
      ylab = "Number of Steps", main = "Time Series of Average Steps Taken", colour = Type)

```

